export const ipcEnum = {
  showMainMenu: 'show-main-menu',
  setIgnoreMouseEvent: 'set-ignore-mouse-event',
  sql: 'sql',
  getAllType: 'get-all-type',
  getTypeListByIdList: 'get-type-list-by-id-list',
  getAllCategory: 'get-all-category',
  listCategoryByTid: 'list-category-by-tid',
  addCategory: 'add-category',
  editCategory: 'update-category',
  removeCategory: 'remove-category',
  getArticleById: 'get-article-by-id',
  listArticleByTidAndCid: 'list-article-by-tid-and-cid',
  listAllArticle: 'list-all-article',
  listAllArticleNoCategory: 'list-all-article-no-category',
  editArticle: 'edit-article',
  removeArticle: 'remove-article',
  addArticle: 'add-article',
  searchArticle: 'search-article',
  // 网页树相关 IPC 事件
  getWebTreeByTypeId: 'get-web-tree-by-type-id',
  getWebTreeByTypeIdAndCategoryId: 'get-web-tree-by-type-id-and-category-id',
  getWebTreeByTypeIdAndNullCategory: 'get-web-tree-by-type-id-and-null-category',
  getWebTreeNodeById: 'get-web-tree-node-by-id',
  updateWebTreeNodeCategoryId: 'update-web-tree-node-category-id',
  updateWebTreeNodeCategoryIdRecursive: 'update-web-tree-node-category-id-recursive',
  addWebTreeNode: 'add-web-tree-node',
  updateWebTreeNode: 'update-web-tree-node',
  removeWebTreeNode: 'remove-web-tree-node',
  moveWebTreeNode: 'move-web-tree-node',
  searchWebTree: 'search-web-tree',
  searchWebTreeByShortcut: 'search-web-tree-by-shortcut',
  reorderWebTreeNodes: 'reorder-web-tree-nodes',
  setFolderAsCategory: 'set-folder-as-category',
  // 图标获取 IPC 事件
  fetchFavicon: 'fetch-favicon',
  // 书签导入 IPC 事件
  importBookmarks: 'import-bookmarks',
  showWindow: 'show-window',
  showWindowExclusive: 'show-window-exclusive',
  hideWindow: 'hide-window',
  openExternal: 'open-external',
  // 设置相关 IPC 事件
  getAllSettings: 'get-all-settings',
  getSettingByKey: 'get-setting-by-key',
  setSetting: 'set-setting',
  deleteSetting: 'delete-setting',
  // 快捷键相关 IPC 事件
  reloadShortcut: 'reload-shortcut',
  // 随手记相关 IPC 事件
  addNote: 'add-note',
  editNote: 'edit-note',
  removeNote: 'remove-note',
  listAllNote: 'list-all-note',
  getNoteById: 'get-note-by-id',
  // 开机自启动相关 IPC 事件
  toggleAutoLaunch: 'toggle-auto-launch',
  getAutoLaunchStatus: 'get-auto-launch-status',
  // OSS 上传相关 IPC 事件
  ossUpload: 'oss-upload',
  // 使用 Electron 原生对话框选择并上传图片，避免 packaged 下 input[type=file] 白屏
  pickAndUploadImages: 'pick-and-upload-images',
  // 命令配置相关 IPC 事件
  listCommands: 'list-commands',
  searchCommands: 'search-commands',
  addCommand: 'add-command',
  updateCommand: 'update-command',
  removeCommand: 'remove-command',
  // 命令执行与日志相关 IPC 事件
  runCommand: 'run-command',
  stopCommand: 'stop-command',
  runUnifiedCommands: 'run-unified-commands',
  stopUnifiedCommands: 'stop-unified-commands',
  getRunningCommands: 'get-running-commands',
  getCommandLogs: 'get-command-logs',
  dismissCommandInstance: 'dismiss-command-instance'
}
