export const ipcEnum = {
  showMainMenu: 'show-main-menu',
  setIgnoreMouseEvent: 'set-ignore-mouse-event',
  sql: 'sql',
  getAllType: 'get-all-type',
  getTypeListByIdList: 'get-type-list-by-id-list',
  getAllCategory: 'get-all-category',
  listCategoryByTid: 'list-category-by-tid',
  addCategory: 'add-category',
  editCategory: 'update-category',
  removeCategory: 'remove-category',
  getArticleById: 'get-article-by-id',
  listArticleByTidAndCid: 'list-article-by-tid-and-cid',
  listAllArticle: 'list-all-article',
  listAllArticleNoCategory: 'list-all-article-no-category',
  editArticle: 'edit-article',
  removeArticle: 'remove-article',
  addArticle: 'add-article',
}
